# Generated by Django 3.1.1 on 2020-09-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0003_todo_todogroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='del_yn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='reg_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todogroup',
            name='del_yn',
            field=models.BooleanField(default=False),
        ),
    ]
